version: 2
updates:
  - package-ecosystem: npm
    directory: "/packages/dashboard"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: "/packages/dnslink-api"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: "/packages/handshake-api"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: "/packages/health-check"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: "/packages/website"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/docker/accounts"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/docker/caddy"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/docker/handshake"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/docker/nginx"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/docker/sia"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/packages/dashboard"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/packages/dnslink-api"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/packages/handshake-api"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/packages/health-check"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/packages/website"
    schedule:
      interval: weekly
