version: "3.7"

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  sia:
    environment:
      - MONGODB_URI=mongodb://${SKYNET_DB_HOST}:${SKYNET_DB_PORT}
      - MONGODB_USER=${SKYNET_DB_USER}
      - MONGODB_PASSWORD=${SKYNET_DB_PASS}

  mongo:
    image: mongo:4.4.1
    command: --keyFile=/data/mgkey --replSet=${SKYNET_DB_REPLICASET:-skynet}
    container_name: mongo
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ./docker/data/mongo/db:/data/db
      - ./docker/data/mongo/mgkey:/data/mgkey:rw
    networks:
      shared:
        ipv4_address: 10.10.10.71
    ports:
      - "${SKYNET_DB_PORT}:27017"
