name: skynet-webportal CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn

      - name: "Static code analysis: handshake-api"
        run: yarn workspace handshake-api prettier --check .

      - name: "Static code analysis: health-check"
        run: yarn workspace health-check prettier --check .

      - name: "Static code analysis: webapp"
        run: yarn workspace webapp prettier --check .

      - name: "Build webapp"
        run: yarn workspace webapp build
        env:
          GATSBY_API_URL: "https://siasky.net"

      - name: "Upload to Skynet"
        uses: kwypchlo/deploy-to-skynet-action@v1.9
        with:
          upload-dir: packages/webapp/public
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cypress run
        uses: cypress-io/github-action@v1
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          working-directory: packages/webapp
          record: true
          start: npx http-server public --port 8000
          wait-on: "http://localhost:8000"
