name: Deploy website to Skynet

on:
  pull_request:
    paths:
      - "packages/website/**"

defaults:
  run:
    working-directory: packages/website

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: yarn
      - run: yarn build

      - name: "Integration tests"
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          working-directory: packages/website
          install: false
          record: true
          start: yarn serve
          wait-on: "http://127.0.0.1:9000"

      - name: "Deploy to Skynet"
        uses: kwypchlo/deploy-to-skynet-action@main
        with:
          upload-dir: packages/website/public
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-seed: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && secrets.WEBSITE_REGISTRY_SEED || '' }}
